FORMAT: 1A
HOST: http://hub.wattbike.com

# Wattbike

This API provides access to the **Wattbike** service.

## Status API [/api/ranking/]

### Get the status API  [GET]
+ Request (application/json)

    + Headers
            
            X-API-KEY : AY7JsQof82R3NTaZu0KSzJJLiR364cSk
            Accept : application/json

+ Response 200 (application/json)
            
            {
                "status": "live"
            }

## Update Account Registration [/api/ranking/users]

### Update account password with charakters less then 6 symbols [PUT]

You may update password using this action. It takes a JSON
object containing an account email addres and a new password.

+ Request (application/json)

        {
            "emailAddress" : {dynamicEmail},
            "password" : "dd"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
