FORMAT: 1A
HOST: http://hub.wattbike.com/

# Wattbike

This API provides access to the **Wattbike** service.

## Status API [/api/ranking]

### Get the status API  [GET]
+ Request (application/json)

    + Headers
            
            X-API-KEY : AY7JsQof82R3NTaZu0KSzJJLiR364cSk
            Accept : application/json

+ Response 200 (application/json)
            
            {
                "status": "live"
            }

## Account Registration [/api/ranking/users]

### Update account password [PUT]

You may update password using this action. It takes a JSON
object containing an account email address and a new password. 
- If the new password is less than 6 characters, service returns error with status code 400.
- If the new password is more than 6 characters, service returns JSON object with user id and authantication token.

+ Request (application/json)

    + Headers

            X-API-KEY : AY7JsQof82R3NTaZu0KSzJJLiR364cSk
            Accept : application/json

    + Body

            {
                "emailAddress": "{dynamicEmail}",
                "password": "dd"
            }
   
+ Response 400 (application/json)

        {
            "error": "Password too short - minimum 6 characters"
        }

+ Response 200 (application/json)

        {
            "authenticationToken": "044548a18337899b8dac630fe9d5f2bb",
            "userId": "648563f5968a2586"
        }

### Account sign-in [POST]

You may sign-in in the application using this action. 
It takes a JSON object containing an account email address and an account password

+ Request (application/json)

    + Headers

            X-API-KEY : AY7JsQof82R3NTaZu0KSzJJLiR364cSk
            Accept : application/json

    + Body

            {
                "emailAddress": "andymccorkell@gmail.com",
                "password": "hQeqLhnM22"
            }

+ Response 200 (application/json)

        {
            "authenticationToken": "f89f3332a012b1beb4e66d5f783a04e8",
            "userId": "92855eb01cdd9fa1"
        }
   
## Token Verification [/api/ranking/auths]

### Send token verification [POST]

You may send token verification using this action. It takes a JSON
object containing a token. If this is a valid token, 
service return user account releated to this token and the same token.

+ Request (application/json)

    + Headers

            X-API-KEY : AY7JsQof82R3NTaZu0KSzJJLiR364cSk
            Accept : application/json

    + Body

            {
                 "authenticationToken": "f89f3332a012b1beb4e66d5f783a04e8"
            }
            
+ Response 200 (application/json)

        {
            "account": "andymccorkell@gmail.com",
            "authenticationToken": "f89f3332a012b1beb4e66d5f783a04e8"
        }
